### ISSUE TITLE
Bug: Add event to cms.kvarteret.no lead to crashing /events page

### ISSUE THREAD

**Issue by mathiash98** [kvarteret/kvarteret.no#36]
Error:
```
TypeError: Cannot read properties of undefined (reading 'title')
    at p (events-a63a09d3fc20bda6.js:1:3065)
    at oo (framework-0bff4c72fef67389.js:1:59412)
    at Ku (framework-0bff4c72fef67389.js:1:111712)
    at Li (framework-0bff4c72fef67389.js:1:98953)
    at Ni (framework-0bff4c72fef67389.js:1:98881)
    at Pi (framework-0bff4c72fef67389.js:1:98744)
    at bi (framework-0bff4c72fef67389.js:1:95710)
    at framework-0bff4c72fef67389.js:1:45204
    at t.unstable_runWithPriority (framework-0bff4c72fef67389.js:1:129338)
    at Ql (framework-0bff4c72fef67389.js:1:44981)
    at Yl (framework-0bff4c72fef67389.js:1:45149)
    at Kl (framework-0bff4c72fef67389.js:1:45084)
    at hi (framework-0bff4c72fef67389.js:1:93087)
    at zo (framework-0bff4c72fef67389.js:1:64737)
    at events-a63a09d3fc20bda6.js:1:3630
    at l (main-415c80aa8e363d8d.js:1:110568)
    at Generator._invoke (main-415c80aa8e363d8d.js:1:110356)
    at Generator.P.forEach.e.<computed> [as next] (main-415c80aa8e363d8d.js:1:110991)
    at b (events-a63a09d3fc20bda6.js:1:389)
    at a (events-a63a09d3fc20bda6.js:1:3778)
```

Put event back to draft -> /events subpgage works again

Happening as it is possible to add an event without english/norwegian translation. So we need to default at least show something...

**Comment by mathiash98** [comment]
@Cengelsen Solved by downloading all translations and then fallback to whatever translation exists if any language is missing
